<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="CustomerNameSvcDefinitions"
     targetNamespace="http://com/sample/customer"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:WL5G3N1="http://com/sample/customer"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="CustomerService">
        <plnk:role name="CustomerNameService" portType="WL5G3N1:CustomerNameService"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://com/sample/customer" location="CustomerNameService.wsdl"/>
</wsdl:definitions>
