<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBPollerStudentSvc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:tns="http://BPEL_DBPoller/WriteFile_StudentSvc" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/DBPollerStudentSvc_table.xsd"/>
            <oracle-xsl-mapper:rootElement name="StudentsCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBPollerStudentSvc"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/nxsd_student.xsd"/>
            <oracle-xsl-mapper:rootElement name="studentlist" namespace="http://BPEL_DBPoller/WriteFile_StudentSvc"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [THU OCT 13 16:56:14 IST 2022].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:studentlist>
         <xsl:for-each select="/ns0:StudentsCollection/ns0:Students">
            <tns:student>
               <tns:Stud_Id>
                  <xsl:value-of select="ns0:studentId"/>
               </tns:Stud_Id>
               <tns:Stud_Name>
                  <xsl:value-of select="ns0:studentName"/>
               </tns:Stud_Name>
               <tns:Stud_Class>
                  <xsl:value-of select="ns0:studentClass"/>
               </tns:Stud_Class>
               <tns:Stud_School>
                  <xsl:value-of select="ns0:studentSchool"/>
               </tns:Stud_School>
               <tns:Stud_Grad_Status>
                  <xsl:value-of select="ns0:studentGradStatus"/>
               </tns:Stud_Grad_Status>
            </tns:student>
         </xsl:for-each>
      </tns:studentlist>
   </xsl:template>
</xsl:stylesheet>
